# Generated by Django 5.1.1 on 2024-09-08 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=2000)),
                ('isbn', models.IntegerField()),
                ('category', models.CharField(max_length=50)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('is_borrowed', models.BooleanField(default=False)),
                ('is_reserved', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='authors.authors')),
            ],
        ),
    ]
