# Generated by Django 5.1.1 on 2024-09-08 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserve_date', models.DateField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserves', to='books.books')),
                ('reserver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserves', to='user_profile.user')),
            ],
        ),
    ]
