# Generated by Django 5.1.1 on 2024-09-12 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowtransactions',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
    ]
