# Generated by Django 5.1.1 on 2024-09-13 20:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrows', '0002_borrowtransactions_is_flagged'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowtransactions',
            name='end_borrow_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
