# Generated by Django 5.1.1 on 2024-09-13 20:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrows', '0004_alter_borrowtransactions_end_borrow_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowtransactions',
            name='end_borrow_date',
            field=models.DateField(default=datetime.date(2024, 9, 14)),
        ),
    ]
