# Generated by Django 5.1.1 on 2024-09-18 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0002_alter_books_isbn'),
        ('borrows', '0008_alter_borrowtransactions_end_borrow_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewAndRatings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(blank=True, max_length=500, null=True)),
                ('rating', models.IntegerField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='books.books')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='borrows.borrowtransactions')),
            ],
        ),
    ]
