# Generated by Django 5.1.1 on 2024-09-13 20:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0018_alter_user_registration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_reserves',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='registration_date',
            field=models.DateField(default=datetime.datetime(2024, 9, 13, 20, 45, 42, 240405, tzinfo=datetime.timezone.utc)),
        ),
    ]
