# Generated by Django 5.1.1 on 2024-09-16 14:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0029_rename_total_reserves_user_total_borrows_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='registration_date',
            field=models.DateField(default=datetime.datetime(2024, 9, 16, 14, 35, 30, 661052, tzinfo=datetime.timezone.utc)),
        ),
    ]
